version: '3.8'

services:
  database:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    deploy:
      resources:
        reservations:
          cpus: '2'
          memory: 2GB
    environment:
      SA_PASSWORD: myStrongPassword12#
      ACCEPT_EULA: Y
    volumes:
      - sqldata:/var/opt/mssql

  webapp:
    container_name: webapp
    domainname: nikkivasilev
    image: nikkivasilevbazarscr.azurecr.io/bazarsa
    ports:
      - "80:80"
    restart: on-failure

volumes:
  sqldata:
    driver: azure_file
    driver_opts:
      share_name: sql-volume
      storage_account_name: nikkivasilevbazarsa
